version: '3.8'

services:
  # 1. Neo4j DB
  neo4j:
    image: neo4j:latest
    container_name: olm-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_bolt_advertised__address=sfolm.iptime.org:7687
      - NEO4J_server_config_strict__validation_enabled=false
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - ./neo4j_data:/data
      - ./neo4j_plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:7474 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10

  # 2. DB Viewer
  db-viewer:
    build:
      context: .
      dockerfile: Dockerfile.viewer
    image: custom-viewer-image
    container_name: olm-db-viewer
    ports:
      - "8501:8501"
    environment:
      - PROJECT_ROOT=/app
    volumes:
      - .:/app
      - ./database:/app/database
    depends_on:
      - backend
    command: streamlit run db_viewer.py --server.port 8501 --server.address 0.0.0.0 --server.baseUrlPath=/viewer --server.enableCORS=false --server.enableXsrfProtection=false

  # 3. Backend
  backend:
    build: ./backend
    container_name: olm-backend
    expose:
      - "${BACKEND_PORT}"
    environment:
      - PYTHONUNBUFFERED=1
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DATASET_DIR=/app/dataset
      - DATABASE_DIR=/app/database
      - API_BASE_URL=${VITE_API_URL}
    volumes:
      - ./backend:/app
      - ./dataset:/app/dataset
      - ./database:/app/database
    command: uvicorn app.api:app --host 0.0.0.0 --port ${BACKEND_PORT} --reload
    depends_on:
      neo4j:
        condition: service_healthy

  # 4. Frontend
  # [옵션 1] 개발 모드
  frontend:
    build:
      context: ./frontend
      target: development
      args:
        - VITE_API_URL=${VITE_API_URL}
    container_name: olm-frontend
    ports:
      - "${MAIN_PORT}:${MAIN_PORT}"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_TARGET=http://olm-backend:${BACKEND_PORT}
      - VITE_API_URL=${VITE_API_URL}
    command: npm run dev -- --host --port ${MAIN_PORT} --force
    depends_on:
      - backend

  # [옵션 2] 배포 모드
  # frontend:
  #   build:
  #     context: ./frontend
  #     target: production
  #     args:
  #       - VITE_API_URL=${VITE_API_URL}
  #   container_name: olm-frontend
  #   expose:
  #     - "80"
  #   restart: always
  #   depends_on:
  #     - backend

  # nginx-proxy:
  #   image: nginx:stable-alpine
  #   container_name: olm-nginx
  #   ports:
  #     - "${MAIN_PORT}:80"
  #   volumes:
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - frontend
